version: '3.2'

services:
  db-movies-ws:
    image: postgres:9.6.1
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_DB=db_movies_ws
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  movies-ws:
    build:
      context: .
      dockerfile: Dockerfile
    image: movies-ws
    restart: always
    expose:
      - 8080
    ports:
      - 8090:8080
    dns: 8.8.8.8
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-movies-ws:5432/db_movies_ws
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create-drop
    depends_on:
      - db-movies-ws