spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_movies_ws
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      temp:
        use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

